.PHONY: default install clean debug release build test format generate 

ARCH=$(shell uname -m)
INSTALL=install
SHELL=bash

# configure.mk is generated by ./configure, it defines $(LOAD) among other things
include configure.mk

default: target/release/sonar

target/release/sonar: src/*.rs src/*/*.rs gpuapi/$(ARCH)/*.a
	$(LOAD) ; cargo build --release

src/json_tags.rs: util/formats/newfmt/types.go
	$(MAKE) generate

# FIXME: This needs to deal with a prefix for the target dir, not sure what yet.  The sources are
# assumed to be relative to the current directory in a build setting.

install: target/release/sonar
	$(INSTALL) -p -D -m 0755 -t /usr/local/lib/sonar target/release-with-debug/sonar
	$(INSTALL) -p -D -m 0644 -t /usr/local/lib/sonar build-dist/rpm-assets/*

clean:
	$(LOAD) ; cargo clean
	$(LOAD) ; ( cd util ; $(MAKE) clean )
	rm -f configure.mk

# This is where the real action is, see doc/HOWTO-DEVELOP.md.
#
# TODO: Get rid of these?

debug:
	$(LOAD) ; CARGO_TARGET_DIR=target/$(ARCH) cargo build

release:
	$(LOAD) ; CARGO_TARGET_DIR=target/$(ARCH) cargo build --release )

build: generate format release

# Build everything then run all test suites
test: debug release
	$(LOAD) ; cargo test
	$(LOAD) ; ( cd util ; $(MAKE) test )
	$(LOAD) ; ( cd tests; $(MAKE) test )

# Reformat all sources
format:
	$(LOAD) ; cargo fmt
	$(LOAD) ; ( cd util ; $(MAKE) format )
	$(LOAD) ; ( cd tests ; $(MAKE) format )
	$(LOAD) ; ( cd gpuapi ; $(MAKE) format )

# (Re)generate all files that are generated
generate:
	$(LOAD) ; ( cd build-dist ; $(MAKE) generate )
	$(LOAD) ; ( cd util ; $(MAKE) generate )
	$(LOAD) ; ( cd tests ; $(MAKE) generate )

# https://github.com/lars-t-hansen/gotags, you can also use etags here for less interesting info
RSSRC=$(shell find src -name '*.rs')
GOSRC=$(shell find util -name '*.go')
CSRC=$(shell find gpuapi -name '*.c' -o -name '*.h')
SRC=$(RSSRC) $(GOSRC) $(CSRC) build.rs
TAGS: $(SRC)
	@gotags $(SRC)
	@echo "TAGS rebuilt"
