#!/usr/bin/env bash

echo "// Generated by version.bash from ../../Cargo.toml, DO NOT EDIT" > version.go
echo "" >> version.go
echo package main >> version.go
echo "" >> version.go
echo const $(grep '^version =' ../../Cargo.toml) >> version.go
