/* automatically generated by rust-bindgen 0.73.2 */

unsafe extern "C" {
    pub fn amdml_device_get_count(count: *mut u32) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct amdml_card_info_t {
    pub bus_addr: [::std::os::raw::c_char; 80usize],
    pub model: [::std::os::raw::c_char; 256usize],
    pub driver: [::std::os::raw::c_char; 64usize],
    pub firmware: [::std::os::raw::c_char; 32usize],
    pub uuid: [::std::os::raw::c_char; 96usize],
    pub totalmem: u64,
    pub power_limit: ::std::os::raw::c_uint,
    pub min_power_limit: ::std::os::raw::c_uint,
    pub max_power_limit: ::std::os::raw::c_uint,
    pub min_ce_clock: ::std::os::raw::c_uint,
    pub max_ce_clock: ::std::os::raw::c_uint,
    pub min_mem_clock: ::std::os::raw::c_uint,
    pub max_mem_clock: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdml_card_info_t"][::std::mem::size_of::<amdml_card_info_t>() - 568usize];
    ["Alignment of amdml_card_info_t"][::std::mem::align_of::<amdml_card_info_t>() - 8usize];
    ["Offset of field: amdml_card_info_t::bus_addr"]
        [::std::mem::offset_of!(amdml_card_info_t, bus_addr) - 0usize];
    ["Offset of field: amdml_card_info_t::model"]
        [::std::mem::offset_of!(amdml_card_info_t, model) - 80usize];
    ["Offset of field: amdml_card_info_t::driver"]
        [::std::mem::offset_of!(amdml_card_info_t, driver) - 336usize];
    ["Offset of field: amdml_card_info_t::firmware"]
        [::std::mem::offset_of!(amdml_card_info_t, firmware) - 400usize];
    ["Offset of field: amdml_card_info_t::uuid"]
        [::std::mem::offset_of!(amdml_card_info_t, uuid) - 432usize];
    ["Offset of field: amdml_card_info_t::totalmem"]
        [::std::mem::offset_of!(amdml_card_info_t, totalmem) - 528usize];
    ["Offset of field: amdml_card_info_t::power_limit"]
        [::std::mem::offset_of!(amdml_card_info_t, power_limit) - 536usize];
    ["Offset of field: amdml_card_info_t::min_power_limit"]
        [::std::mem::offset_of!(amdml_card_info_t, min_power_limit) - 540usize];
    ["Offset of field: amdml_card_info_t::max_power_limit"]
        [::std::mem::offset_of!(amdml_card_info_t, max_power_limit) - 544usize];
    ["Offset of field: amdml_card_info_t::min_ce_clock"]
        [::std::mem::offset_of!(amdml_card_info_t, min_ce_clock) - 548usize];
    ["Offset of field: amdml_card_info_t::max_ce_clock"]
        [::std::mem::offset_of!(amdml_card_info_t, max_ce_clock) - 552usize];
    ["Offset of field: amdml_card_info_t::min_mem_clock"]
        [::std::mem::offset_of!(amdml_card_info_t, min_mem_clock) - 556usize];
    ["Offset of field: amdml_card_info_t::max_mem_clock"]
        [::std::mem::offset_of!(amdml_card_info_t, max_mem_clock) - 560usize];
};
impl Default for amdml_card_info_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn amdml_device_get_card_info(
        device_index: u32,
        infobuf: *mut amdml_card_info_t,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct amdml_card_state_t {
    pub fan_speed_pct: f32,
    pub perf_level: ::std::os::raw::c_int,
    pub mem_used: u64,
    pub gpu_util: f32,
    pub mem_util: f32,
    pub temp: ::std::os::raw::c_uint,
    pub power: ::std::os::raw::c_uint,
    pub power_limit: ::std::os::raw::c_uint,
    pub ce_clock: ::std::os::raw::c_uint,
    pub mem_clock: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdml_card_state_t"][::std::mem::size_of::<amdml_card_state_t>() - 48usize];
    ["Alignment of amdml_card_state_t"][::std::mem::align_of::<amdml_card_state_t>() - 8usize];
    ["Offset of field: amdml_card_state_t::fan_speed_pct"]
        [::std::mem::offset_of!(amdml_card_state_t, fan_speed_pct) - 0usize];
    ["Offset of field: amdml_card_state_t::perf_level"]
        [::std::mem::offset_of!(amdml_card_state_t, perf_level) - 4usize];
    ["Offset of field: amdml_card_state_t::mem_used"]
        [::std::mem::offset_of!(amdml_card_state_t, mem_used) - 8usize];
    ["Offset of field: amdml_card_state_t::gpu_util"]
        [::std::mem::offset_of!(amdml_card_state_t, gpu_util) - 16usize];
    ["Offset of field: amdml_card_state_t::mem_util"]
        [::std::mem::offset_of!(amdml_card_state_t, mem_util) - 20usize];
    ["Offset of field: amdml_card_state_t::temp"]
        [::std::mem::offset_of!(amdml_card_state_t, temp) - 24usize];
    ["Offset of field: amdml_card_state_t::power"]
        [::std::mem::offset_of!(amdml_card_state_t, power) - 28usize];
    ["Offset of field: amdml_card_state_t::power_limit"]
        [::std::mem::offset_of!(amdml_card_state_t, power_limit) - 32usize];
    ["Offset of field: amdml_card_state_t::ce_clock"]
        [::std::mem::offset_of!(amdml_card_state_t, ce_clock) - 36usize];
    ["Offset of field: amdml_card_state_t::mem_clock"]
        [::std::mem::offset_of!(amdml_card_state_t, mem_clock) - 40usize];
};
unsafe extern "C" {
    pub fn amdml_device_get_card_state(
        device_index: u32,
        infobuf: *mut amdml_card_state_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn amdml_device_probe_processes(count: *mut u32) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct amdml_gpu_process_t {
    pub pid: u32,
    pub cards: u32,
    pub gpu_util: u32,
    pub mem_util: u32,
    pub mem_size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of amdml_gpu_process_t"][::std::mem::size_of::<amdml_gpu_process_t>() - 24usize];
    ["Alignment of amdml_gpu_process_t"][::std::mem::align_of::<amdml_gpu_process_t>() - 8usize];
    ["Offset of field: amdml_gpu_process_t::pid"]
        [::std::mem::offset_of!(amdml_gpu_process_t, pid) - 0usize];
    ["Offset of field: amdml_gpu_process_t::cards"]
        [::std::mem::offset_of!(amdml_gpu_process_t, cards) - 4usize];
    ["Offset of field: amdml_gpu_process_t::gpu_util"]
        [::std::mem::offset_of!(amdml_gpu_process_t, gpu_util) - 8usize];
    ["Offset of field: amdml_gpu_process_t::mem_util"]
        [::std::mem::offset_of!(amdml_gpu_process_t, mem_util) - 12usize];
    ["Offset of field: amdml_gpu_process_t::mem_size"]
        [::std::mem::offset_of!(amdml_gpu_process_t, mem_size) - 16usize];
};
unsafe extern "C" {
    pub fn amdml_get_process(
        process_index: u32,
        infobuf: *mut amdml_gpu_process_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn amdml_free_processes();
}
