/* automatically generated by rust-bindgen 0.73.2 */

unsafe extern "C" {
    pub fn fakegpu_device_get_count(count: *mut u32) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct fakegpu_card_info_t {
    pub bus_addr: [::std::os::raw::c_char; 256usize],
    pub model: [::std::os::raw::c_char; 256usize],
    pub driver: [::std::os::raw::c_char; 256usize],
    pub firmware: [::std::os::raw::c_char; 256usize],
    pub uuid: [::std::os::raw::c_char; 256usize],
    pub totalmem: u64,
    pub max_ce_clock: ::std::os::raw::c_uint,
    pub max_power_limit: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fakegpu_card_info_t"][::std::mem::size_of::<fakegpu_card_info_t>() - 1296usize];
    ["Alignment of fakegpu_card_info_t"][::std::mem::align_of::<fakegpu_card_info_t>() - 8usize];
    ["Offset of field: fakegpu_card_info_t::bus_addr"]
        [::std::mem::offset_of!(fakegpu_card_info_t, bus_addr) - 0usize];
    ["Offset of field: fakegpu_card_info_t::model"]
        [::std::mem::offset_of!(fakegpu_card_info_t, model) - 256usize];
    ["Offset of field: fakegpu_card_info_t::driver"]
        [::std::mem::offset_of!(fakegpu_card_info_t, driver) - 512usize];
    ["Offset of field: fakegpu_card_info_t::firmware"]
        [::std::mem::offset_of!(fakegpu_card_info_t, firmware) - 768usize];
    ["Offset of field: fakegpu_card_info_t::uuid"]
        [::std::mem::offset_of!(fakegpu_card_info_t, uuid) - 1024usize];
    ["Offset of field: fakegpu_card_info_t::totalmem"]
        [::std::mem::offset_of!(fakegpu_card_info_t, totalmem) - 1280usize];
    ["Offset of field: fakegpu_card_info_t::max_ce_clock"]
        [::std::mem::offset_of!(fakegpu_card_info_t, max_ce_clock) - 1288usize];
    ["Offset of field: fakegpu_card_info_t::max_power_limit"]
        [::std::mem::offset_of!(fakegpu_card_info_t, max_power_limit) - 1292usize];
};
impl Default for fakegpu_card_info_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn fakegpu_device_get_card_info(
        device_index: u32,
        infobuf: *mut fakegpu_card_info_t,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct fakegpu_card_state_t {
    pub gpu_util: f32,
    pub mem_util: f32,
    pub mem_used: u64,
    pub temp: ::std::os::raw::c_uint,
    pub power: ::std::os::raw::c_uint,
    pub ce_clock: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fakegpu_card_state_t"][::std::mem::size_of::<fakegpu_card_state_t>() - 32usize];
    ["Alignment of fakegpu_card_state_t"][::std::mem::align_of::<fakegpu_card_state_t>() - 8usize];
    ["Offset of field: fakegpu_card_state_t::gpu_util"]
        [::std::mem::offset_of!(fakegpu_card_state_t, gpu_util) - 0usize];
    ["Offset of field: fakegpu_card_state_t::mem_util"]
        [::std::mem::offset_of!(fakegpu_card_state_t, mem_util) - 4usize];
    ["Offset of field: fakegpu_card_state_t::mem_used"]
        [::std::mem::offset_of!(fakegpu_card_state_t, mem_used) - 8usize];
    ["Offset of field: fakegpu_card_state_t::temp"]
        [::std::mem::offset_of!(fakegpu_card_state_t, temp) - 16usize];
    ["Offset of field: fakegpu_card_state_t::power"]
        [::std::mem::offset_of!(fakegpu_card_state_t, power) - 20usize];
    ["Offset of field: fakegpu_card_state_t::ce_clock"]
        [::std::mem::offset_of!(fakegpu_card_state_t, ce_clock) - 24usize];
};
unsafe extern "C" {
    pub fn fakegpu_device_get_card_state(
        device_index: u32,
        infobuf: *mut fakegpu_card_state_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fakegpu_device_probe_processes(
        device_index: u32,
        count: *mut u32,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct fakegpu_gpu_process_t {
    pub pid: u32,
    pub mem_util: u32,
    pub gpu_util: u32,
    pub mem_size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of fakegpu_gpu_process_t"][::std::mem::size_of::<fakegpu_gpu_process_t>() - 24usize];
    ["Alignment of fakegpu_gpu_process_t"]
        [::std::mem::align_of::<fakegpu_gpu_process_t>() - 8usize];
    ["Offset of field: fakegpu_gpu_process_t::pid"]
        [::std::mem::offset_of!(fakegpu_gpu_process_t, pid) - 0usize];
    ["Offset of field: fakegpu_gpu_process_t::mem_util"]
        [::std::mem::offset_of!(fakegpu_gpu_process_t, mem_util) - 4usize];
    ["Offset of field: fakegpu_gpu_process_t::gpu_util"]
        [::std::mem::offset_of!(fakegpu_gpu_process_t, gpu_util) - 8usize];
    ["Offset of field: fakegpu_gpu_process_t::mem_size"]
        [::std::mem::offset_of!(fakegpu_gpu_process_t, mem_size) - 16usize];
};
unsafe extern "C" {
    pub fn fakegpu_get_process(
        process_index: u32,
        infobuf: *mut fakegpu_gpu_process_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn fakegpu_free_processes();
}
