/* automatically generated by rust-bindgen 0.73.2 */

unsafe extern "C" {
    pub fn nvml_device_get_count(count: *mut u32) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct nvml_card_info {
    pub bus_addr: [::std::os::raw::c_char; 80usize],
    pub model: [::std::os::raw::c_char; 96usize],
    pub architecture: [::std::os::raw::c_char; 32usize],
    pub driver: [::std::os::raw::c_char; 80usize],
    pub firmware: [::std::os::raw::c_char; 32usize],
    pub uuid: [::std::os::raw::c_char; 96usize],
    pub totalmem: u64,
    pub power_limit: ::std::os::raw::c_uint,
    pub min_power_limit: ::std::os::raw::c_uint,
    pub max_power_limit: ::std::os::raw::c_uint,
    pub max_ce_clock: ::std::os::raw::c_uint,
    pub max_mem_clock: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nvml_card_info"][::std::mem::size_of::<nvml_card_info>() - 448usize];
    ["Alignment of nvml_card_info"][::std::mem::align_of::<nvml_card_info>() - 8usize];
    ["Offset of field: nvml_card_info::bus_addr"]
        [::std::mem::offset_of!(nvml_card_info, bus_addr) - 0usize];
    ["Offset of field: nvml_card_info::model"]
        [::std::mem::offset_of!(nvml_card_info, model) - 80usize];
    ["Offset of field: nvml_card_info::architecture"]
        [::std::mem::offset_of!(nvml_card_info, architecture) - 176usize];
    ["Offset of field: nvml_card_info::driver"]
        [::std::mem::offset_of!(nvml_card_info, driver) - 208usize];
    ["Offset of field: nvml_card_info::firmware"]
        [::std::mem::offset_of!(nvml_card_info, firmware) - 288usize];
    ["Offset of field: nvml_card_info::uuid"]
        [::std::mem::offset_of!(nvml_card_info, uuid) - 320usize];
    ["Offset of field: nvml_card_info::totalmem"]
        [::std::mem::offset_of!(nvml_card_info, totalmem) - 416usize];
    ["Offset of field: nvml_card_info::power_limit"]
        [::std::mem::offset_of!(nvml_card_info, power_limit) - 424usize];
    ["Offset of field: nvml_card_info::min_power_limit"]
        [::std::mem::offset_of!(nvml_card_info, min_power_limit) - 428usize];
    ["Offset of field: nvml_card_info::max_power_limit"]
        [::std::mem::offset_of!(nvml_card_info, max_power_limit) - 432usize];
    ["Offset of field: nvml_card_info::max_ce_clock"]
        [::std::mem::offset_of!(nvml_card_info, max_ce_clock) - 436usize];
    ["Offset of field: nvml_card_info::max_mem_clock"]
        [::std::mem::offset_of!(nvml_card_info, max_mem_clock) - 440usize];
};
impl Default for nvml_card_info {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
unsafe extern "C" {
    pub fn nvml_device_get_card_info(
        device_index: u32,
        infobuf: *mut nvml_card_info,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nvml_card_state {
    pub fan_speed: ::std::os::raw::c_uint,
    pub compute_mode: ::std::os::raw::c_int,
    pub perf_state: ::std::os::raw::c_int,
    pub mem_reserved: u64,
    pub mem_used: u64,
    pub gpu_util: f32,
    pub mem_util: f32,
    pub temp: ::std::os::raw::c_uint,
    pub power: ::std::os::raw::c_uint,
    pub power_limit: ::std::os::raw::c_uint,
    pub ce_clock: ::std::os::raw::c_uint,
    pub mem_clock: ::std::os::raw::c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nvml_card_state"][::std::mem::size_of::<nvml_card_state>() - 64usize];
    ["Alignment of nvml_card_state"][::std::mem::align_of::<nvml_card_state>() - 8usize];
    ["Offset of field: nvml_card_state::fan_speed"]
        [::std::mem::offset_of!(nvml_card_state, fan_speed) - 0usize];
    ["Offset of field: nvml_card_state::compute_mode"]
        [::std::mem::offset_of!(nvml_card_state, compute_mode) - 4usize];
    ["Offset of field: nvml_card_state::perf_state"]
        [::std::mem::offset_of!(nvml_card_state, perf_state) - 8usize];
    ["Offset of field: nvml_card_state::mem_reserved"]
        [::std::mem::offset_of!(nvml_card_state, mem_reserved) - 16usize];
    ["Offset of field: nvml_card_state::mem_used"]
        [::std::mem::offset_of!(nvml_card_state, mem_used) - 24usize];
    ["Offset of field: nvml_card_state::gpu_util"]
        [::std::mem::offset_of!(nvml_card_state, gpu_util) - 32usize];
    ["Offset of field: nvml_card_state::mem_util"]
        [::std::mem::offset_of!(nvml_card_state, mem_util) - 36usize];
    ["Offset of field: nvml_card_state::temp"]
        [::std::mem::offset_of!(nvml_card_state, temp) - 40usize];
    ["Offset of field: nvml_card_state::power"]
        [::std::mem::offset_of!(nvml_card_state, power) - 44usize];
    ["Offset of field: nvml_card_state::power_limit"]
        [::std::mem::offset_of!(nvml_card_state, power_limit) - 48usize];
    ["Offset of field: nvml_card_state::ce_clock"]
        [::std::mem::offset_of!(nvml_card_state, ce_clock) - 52usize];
    ["Offset of field: nvml_card_state::mem_clock"]
        [::std::mem::offset_of!(nvml_card_state, mem_clock) - 56usize];
};
unsafe extern "C" {
    pub fn nvml_device_get_card_state(
        device_index: u32,
        infobuf: *mut nvml_card_state,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn nvml_device_probe_processes(device_index: u32, count: *mut u32)
    -> ::std::os::raw::c_int;
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct nvml_gpu_process {
    pub pid: u32,
    pub mem_util: u32,
    pub gpu_util: u32,
    pub mem_size: u64,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of nvml_gpu_process"][::std::mem::size_of::<nvml_gpu_process>() - 24usize];
    ["Alignment of nvml_gpu_process"][::std::mem::align_of::<nvml_gpu_process>() - 8usize];
    ["Offset of field: nvml_gpu_process::pid"]
        [::std::mem::offset_of!(nvml_gpu_process, pid) - 0usize];
    ["Offset of field: nvml_gpu_process::mem_util"]
        [::std::mem::offset_of!(nvml_gpu_process, mem_util) - 4usize];
    ["Offset of field: nvml_gpu_process::gpu_util"]
        [::std::mem::offset_of!(nvml_gpu_process, gpu_util) - 8usize];
    ["Offset of field: nvml_gpu_process::mem_size"]
        [::std::mem::offset_of!(nvml_gpu_process, mem_size) - 16usize];
};
unsafe extern "C" {
    pub fn nvml_get_process(
        process_index: u32,
        infobuf: *mut nvml_gpu_process,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn nvml_free_processes();
}
