name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Display Rust version
      run: cargo --version

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose

      # many of the shell tests below need jq
    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Shell tests
      run: |
        cd tests
        ./run_tests.sh

    - name: Output format tests
      run: |
        cd util
        make test
