name: Test that docs are generated

on:
  push:
    branches: [ main, 'release_*' ]
  pull_request:
    branches: [ main, 'release_*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Display Go version
      run: go version

    - name: Regenerate documentation and test
      run: |
        cd tests/ci
        ./go-doc-generate.sh
