name: Test Rust code formatting

on:
  push:
    branches: [ main release_* ]
  pull_request:
    branches: [ main release_* ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Display Rust version
      run: cargo --version

    - name: Format code
      run: |
        cd tests
        ./rust-format.sh
