name: Test minimal Rust version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Rust and set a specific version
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        source $HOME/.cargo/env
        rustup install 1.67.0
        rustup default 1.67.0

    - name: Display Rust version
      run: cargo --version

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose

      # one of the shell tests below needs jq
    - name: Install jq
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Shell tests
      run: |
        cd tests
        ./run_tests.sh
